# Generated by Django 4.2 on 2023-06-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCore', '0002_categorymodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='view',
            field=models.BooleanField(default=False),
        ),
    ]
